{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_sample.py:19: Exception"}, "start": 1565021414833, "stop": 1565021414833, "uuid": "af6812c1-27e4-4024-afa8-684c305ea6b5", "historyId": "4267b07856f57a415e58b1826e81e005", "fullName": "test_sample#test_broken", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_sample"}, {"name": "subSuite"}, {"name": "host", "value": "PRO-IND-283"}, {"name": "thread", "value": "12440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_sample"}]}